SELECT * 
FROM customer;

-- Q1) What is the total revenue generated by male vs female customers.
SELECT gender,SUM(purchase_amount) AS total_revenue
FROM customer
group by gender;

-- Q2) Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
		AND
discount_applied = 'Yes'


-- Q3) Which are the top 5 products with the highest average rating?
SELECT TOP 5 item_purchased AS products, ROUND(AVG(review_rating),2) AS average_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_rating DESC;


-- Q4) Compare the average purchase amounts between Standard and Express shipping.
SELECT shipping_type, AVG(purchase_amount) AS average_purcahse_amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

/* Q5) Do subscribed customers spend more? Compare average spend and total revenue
between subscribed and non-subscribed. */

SELECT subscription_status,COUNT(customer_id) AS total_customer, AVG(purchase_amount) AS average_revenue,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- Q6) Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased, 100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) 
AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;

-- Q7) Segment customers into New, Returning and Loyal based on their total number of previous
-- purchases, and show the count of each segment.

-- Subquery

SELECT customer_segment, COUNT(customer_id) AS total_customers
FROM
	(SELECT *,
		CASE 
		WHEN previous_purchases = 1 THEN 'New'
		WHEN (previous_purchases >=2) AND (previous_purchases <=10) THEN 'Returning'
		ELSE 'Loyal' 
		END AS customer_segment
	FROM customer) AS X
GROUP BY customer_segment
ORDER BY total_customers DESC;


-- With CTE

WITH customer_segment AS
	(SELECT *,
	CASE WHEN previous_purchases = 1 THEN 'New'
		 WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Repeating'
		 ELSE 'Loyal' END AS customer_segment
	FROM customer)

SELECT customer_segment, COUNT(*) AS total_customers
FROM customer_segment
GROUP BY customer_segment;


-- Q8) What are the top 3 most purchased products within each category

SELECT *
FROM(
		SELECT category,item_purchased, count(item_purchased) AS total_quanity,
		ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(item_purchased) DESC) AS Ranks
		FROM customer
		GROUP BY category,item_purchased) AS X
WHERE RANKS<=3;


-- Q9) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;



-- Q10) What is the revenue contribution of each group?
SELECT age_group,SUM(purchase_amount) AS revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;